[package]
name = "marvel-explorer"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]

[dependencies]
dotenv = "0.11.0"
hyper = "0.11.25"
rust-crypto = "0.2.36"
serde = "1.0.42"
serde_derive = "1.0.42"
serde_json = "1.0.16"
url = "1.7.0"
